-- 账单管理表结构
-- 执行前提: 数据库 my_todo_finance 已存在

CREATE TABLE IF NOT EXISTS fin_bill (
    id BIGINT NOT NULL COMMENT '主键ID，雪花算法生成',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    bill_no VARCHAR(64) NOT NULL COMMENT '账单编号，唯一',
    bill_type INT NOT NULL COMMENT '账单类型：1=应收, 2=应付',
    direction INT NOT NULL DEFAULT 1 COMMENT '方向：1=正数(正常), -1=红字(退货)',
    partner_type INT NOT NULL COMMENT '往来单位类型：1=客户, 2=供应商',
    partner_id BIGINT NOT NULL COMMENT '往来单位ID',
    partner_name VARCHAR(128) DEFAULT NULL COMMENT '往来单位名称',
    account_id BIGINT DEFAULT NULL COMMENT '关联资金账户ID',
    currency VARCHAR(16) NOT NULL DEFAULT 'CNY' COMMENT '币种编码',
    exchange_rate DECIMAL(18,6) NOT NULL DEFAULT 1.000000 COMMENT '汇率',
    amount DECIMAL(18,4) NOT NULL COMMENT '账单金额',
    base_amount DECIMAL(18,4) DEFAULT NULL COMMENT '本位币金额（= amount * exchangeRate）',
    paid_amount DECIMAL(18,4) NOT NULL DEFAULT 0.0000 COMMENT '已收/已付金额',
    bill_date DATE NOT NULL COMMENT '账单日期',
    due_date DATE DEFAULT NULL COMMENT '到期日期',
    status INT NOT NULL DEFAULT 0 COMMENT '状态：0=草稿, 1=待审核, 2=已审核, 3=部分收付, 4=已完成, 5=已取消',
    source_type VARCHAR(32) DEFAULT NULL COMMENT '来源类型：PURCHASE/SALE/MANUAL',
    source_id BIGINT DEFAULT NULL COMMENT '来源单据ID',
    source_no VARCHAR(64) DEFAULT NULL COMMENT '来源单据编号',
    audit_status INT NOT NULL DEFAULT 0 COMMENT '审核状态：0=无, 1=待审核, 2=已通过, 3=已驳回',
    audit_by BIGINT DEFAULT NULL COMMENT '审核人ID',
    audit_at DATETIME DEFAULT NULL COMMENT '审核时间',
    audit_remark VARCHAR(512) DEFAULT NULL COMMENT '审核备注',
    remark VARCHAR(512) DEFAULT NULL COMMENT '备注',
    deleted INT NOT NULL DEFAULT 0 COMMENT '软删除标记：0=未删除, 1=已删除',
    created_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT DEFAULT NULL COMMENT '更新人ID',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_bill_no (bill_no),
    KEY idx_tenant_id (tenant_id),
    KEY idx_bill_type (bill_type),
    KEY idx_partner (partner_type, partner_id),
    KEY idx_status (status),
    KEY idx_bill_date (bill_date),
    KEY idx_source (source_type, source_id)
) COMMENT '统一账单表';

CREATE TABLE IF NOT EXISTS fin_bill_invoice (
    id BIGINT NOT NULL COMMENT '主键ID，雪花算法生成',
    tenant_id BIGINT NOT NULL DEFAULT 0 COMMENT '租户ID',
    bill_id BIGINT NOT NULL COMMENT '账单ID',
    invoice_id BIGINT NOT NULL COMMENT '发票ID',
    related_amount DECIMAL(18,4) DEFAULT NULL COMMENT '关联金额',
    deleted INT NOT NULL DEFAULT 0 COMMENT '软删除标记：0=未删除, 1=已删除',
    created_by BIGINT DEFAULT NULL COMMENT '创建人ID',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT DEFAULT NULL COMMENT '更新人ID',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    KEY idx_tenant_id (tenant_id),
    KEY idx_bill_id (bill_id),
    KEY idx_invoice_id (invoice_id)
) COMMENT '账单-发票关联表';
