CREATE TABLE IF NOT EXISTS code_template (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    template_name VARCHAR(128) NOT NULL,
    template_type VARCHAR(32) NOT NULL COMMENT 'ENTITY/MAPPER/SERVICE/CONTROLLER/VUE',
    template_content TEXT NOT NULL,
    description VARCHAR(500),
    deleted INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gen_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    table_name VARCHAR(128) NOT NULL,
    module_name VARCHAR(64),
    package_name VARCHAR(128),
    gen_type VARCHAR(16) DEFAULT 'ALL',
    gen_content TEXT,
    created_by BIGINT DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
