CREATE TABLE IF NOT EXISTS api_definition (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    api_name VARCHAR(128) NOT NULL,
    api_path VARCHAR(256) NOT NULL,
    api_method VARCHAR(10) NOT NULL DEFAULT 'GET',
    description VARCHAR(500),
    version VARCHAR(16) DEFAULT 'v1',
    status INT NOT NULL DEFAULT 1 COMMENT '0=下线 1=上线 2=审核中',
    deleted INT NOT NULL DEFAULT 0,
    created_by BIGINT DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT DEFAULT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS api_subscription (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    api_id BIGINT NOT NULL,
    subscriber_name VARCHAR(128) NOT NULL,
    api_key VARCHAR(128) NOT NULL,
    call_limit INT NOT NULL DEFAULT 1000,
    call_count INT NOT NULL DEFAULT 0,
    status INT NOT NULL DEFAULT 1,
    expires_at DATETIME,
    deleted INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS api_usage_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    api_id BIGINT NOT NULL,
    subscription_id BIGINT NOT NULL,
    request_time DATETIME NOT NULL,
    response_status INT,
    response_time_ms INT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
