CREATE TABLE IF NOT EXISTS error_category (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(128) NOT NULL,
    category_code VARCHAR(64) NOT NULL UNIQUE,
    description VARCHAR(500),
    deleted INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS error_solution (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    category_id BIGINT NOT NULL,
    error_code VARCHAR(64) NOT NULL,
    error_message VARCHAR(500),
    cause_description TEXT,
    solution TEXT,
    deleted INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
