CREATE TABLE IF NOT EXISTS trace_config (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    service_name VARCHAR(128) NOT NULL,
    sample_rate DECIMAL(5,4) NOT NULL DEFAULT 1.0000,
    enabled INT NOT NULL DEFAULT 1,
    deleted INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trace_alert (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL DEFAULT 0,
    alert_name VARCHAR(128) NOT NULL,
    metric_type VARCHAR(32) NOT NULL COMMENT 'RESPONSE_TIME/ERROR_RATE/THROUGHPUT',
    threshold DECIMAL(18,4) NOT NULL,
    condition_type VARCHAR(16) NOT NULL DEFAULT 'GT',
    service_name VARCHAR(128),
    enabled INT NOT NULL DEFAULT 1,
    notify_type VARCHAR(16) DEFAULT 'LOG',
    deleted INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
